language: c
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends gcc build-essential libc6-dev gcc-multilib
  - os: osx
    osx_image: xcode8.3
script:
- make
deploy:
  provider: releases
  api_key:
    secure: Oh6GPWPluzdruSPw/NEIzMYmNIUpt79nuGsHsmfHH3OmpX2tAWtrv5kSUQGqnRi1mhtC4cxoH+UsfAcl9e4mxjjHWcbY1aEdHna3sb5OQpxjt9nBjQTgw4P9F8nt04PP5vwnHnjHw6zUZYuLJgT/hkDR3wNFtkJ/LcVdRFvZjeu9aE8eneM7DhGweJzzoUdGnl4VgK7LSYWNEUv1yfgDf52EhZl6mHyvQqbV0RvFr7E4yWpCjDviqi2JYCYzPOL3By8ZSgfHc4IJAJStH/1kbv7Khx7+nEIYWwUwL3C50asli95eL0Wt2DrtZcZB4E1M7C95WKjDkFn1SDZPOUkUvFR7+K8Lu0YE7Sga8qDJJXkoCCNzcrwdRCNwLyIx5Ldga43T1QsqXEp7CmqXv8C0/JriVKfyMhBiHJvxia24fU3Wm0JX9ZgARiIf0pmCjhyxN+9X97mGpWbiZ0v/GkxQNef198Ppb/bOgbDnvOuLVh9NgJSljYLoIiNzDWBjGPECj1pkLye4NY9PT7lqA1ZtH/jDhh63XXXvqZ+CUnQ4sV+p9JlKN+ZKhj8yaKbDN+/AkIqWJ9a1/6tQ1SNsBM+UPiWe6R76Z2qt3XIBV17fHQ+EhYCDV5N/fTEXAA6r/e5y1tAoZxRE11mrgSkwRu3UdEVontZGUDe5TINpAqzICM8=
  on:
    repo: devnull-cz/unix-linux-prog-in-c-src
    tags: true
